### ISSUE TITLE
Config option "max_snapshots": 8 is not persistent (yet?)

### ISSUE THREAD

**Issue by IoTmessenger** [d0ugal/hassio-dropbox-upload#18]
Perhaps I am too fast trying this option, as your documentation does not mention it yet.
I just noticed the remark '**2018-09-10 11:51:06,851 - WARNING - max_snapshots not set. We wont remove old snapshots**' in the Log after a (successful) test of the latest build of the addon.

Of course I tried to add this new config option immediately, as this functionality is on top of my 'most wanted list'.
😃 

After stopping the addon, adding the new config option and save it OK, after starting the addon again it just disappears from the config field.
```
{
  "access_token": "redacted...",
  "dropbox_dir": "/hassio/",
  "max_snapshots": 8
}
```

turns back in to:
```
{
  "access_token": "redacted...",
  "dropbox_dir": "/hassio/"
}
```

**Comment by IoTmessenger** [comment]
It probably still needs to be added to the 'options' part of the [config.json](https://github.com/d0ugal/hassio-dropbox-upload/blob/master/dropbox-upload/config.json):
```
    "options": {
        "access_token": "<YOUR_ACCESS_TOKEN>",
        "dropbox_dir": "<DROPBOX_UPLOAD_LOCATION>"
    },
```

**Comment by d0ugal** [comment]
Yeah, sorry - I didn't mean to merge that change into master. It isn't ready yet.

**Comment by IoTmessenger** [comment]
No worries, not a problem. Nice to know it is coming!

**Comment by IoTmessenger** [comment]
Until the max_snapshot has been implemented, I manually manage the amount of files (Dropbox max limit of 1GB data size). Is there some caching of existing tar files in the backup directory of Hass.io?
When I delete a couple of older snapshots (went from 9 to 5 files) and restart the addon, I halts with an error after processing the still existing files correctly:
```
Log
2018-09-10 13:53:45,259 - INFO - Starting Snapshot backup
2018-09-10 13:53:45,288 - INFO - Backing up 9 snapshots
2018-09-10 13:53:45,289 - INFO - Backing up to Dropbox directory: /hassio
2018-09-10 13:53:45,289 - INFO - Snapshot: 2018-09-09T22_45_07_Snapshot (1/9)
2018-09-10 13:53:45,290 - INFO - Slug: 6496d0e9
2018-09-10 13:53:45,290 - INFO - Created: 2018-09-09T22:45:07.966604+00:00
2018-09-10 13:53:45,290 - INFO - Size: 294.32 MB
2018-09-10 13:53:45,290 - INFO - Uploading to: /hassio/6496d0e9.tar
2018-09-10 13:53:48,756 - INFO - Already found in Dropbox with the same hash
2018-09-10 13:53:48,756 - INFO - Snapshot: 2018-09-08T22_45_28_Snapshot (2/9)
2018-09-10 13:53:48,757 - INFO - Slug: 1918ae4d
2018-09-10 13:53:48,757 - INFO - Created: 2018-09-08T22:45:28.376358+00:00
2018-09-10 13:53:48,757 - INFO - Size: 60.3 MB
2018-09-10 13:53:48,758 - INFO - Uploading to: /hassio/1918ae4d.tar
2018-09-10 13:53:49,708 - INFO - Already found in Dropbox with the same hash
2018-09-10 13:53:49,708 - INFO - Snapshot: 2018-09-07T22_45_35_Snapshot (3/9)
2018-09-10 13:53:49,709 - INFO - Slug: 5ea66f42
2018-09-10 13:53:49,709 - INFO - Created: 2018-09-07T22:45:36.016527+00:00
2018-09-10 13:53:49,709 - INFO - Size: 57.85 MB
2018-09-10 13:53:49,710 - INFO - Uploading to: /hassio/5ea66f42.tar
2018-09-10 13:53:50,588 - INFO - Already found in Dropbox with the same hash
2018-09-10 13:53:50,588 - INFO - Snapshot: 2018-09-07T18_14_35_Snapshot (4/9)
2018-09-10 13:53:50,589 - INFO - Slug: 6b443d38
2018-09-10 13:53:50,589 - INFO - Created: 2018-09-07T18:14:36.005882+00:00
2018-09-10 13:53:50,589 - INFO - Size: 291.05 MB
2018-09-10 13:53:50,589 - INFO - Uploading to: /hassio/6b443d38.tar
2018-09-10 13:53:53,873 - INFO - Already found in Dropbox with the same hash
2018-09-10 13:53:53,874 - INFO - Snapshot: 2018-09-06T22_45_26_Snapshot (5/9)
2018-09-10 13:53:53,875 - INFO - Slug: 1f1aea31
2018-09-10 13:53:53,875 - INFO - Created: 2018-09-06T22:45:26.209800+00:00
2018-09-10 13:53:53,875 - INFO - Size: 57.48 MB
2018-09-10 13:53:53,875 - INFO - Uploading to: /hassio/1f1aea31.tar
2018-09-10 13:53:54,732 - INFO - Already found in Dropbox with the same hash
2018-09-10 13:53:54,732 - INFO - Snapshot: test (6/9)
2018-09-10 13:53:54,733 - ERROR - Unhandled error
Traceback (most recent call last):
  File "upload.py", line 214, in main
    backup(dbx, config, snapshots)
  File "upload.py", line 179, in backup
    process_snapshot(dropbox_dir, dbx, snapshot)
  File "upload.py", line 151, in process_snapshot
    size = bytes_to_human(os.path.getsize(path))
  File "/usr/lib/python3.6/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/backup/cd5196e3.tar'
```

[EDIT] 
After creating a new snapshot, the addon does recognize that a new file has been added to the backup folder and it does still upload the new one OK.
So it was not completely halted. I notice the file counter now has become 10 i.s.o. 6 it should be. It still ends with the error on the first missing (deleted by me) file.

[EDIT 2]
A restart of Hass,io does not fix the error. So the (cached?) contents of the backup directory seem to be  persistent.

**Comment by d0ugal** [comment]
Strange. There is no caching that I am aware of.

When the addon starts, it looks for the snapshots and starts to process them one at time. So if you delete snapshots while it is running it will get confused. However, this should be resolved by restarting.

I'll add something to make sure it verifies the snapshots still exist.

**Comment by IoTmessenger** [comment]
Can be closed now the 'keep' option has been added.
Other issue with manual removing files will not return anymore (also did not return).
