### ISSUE TITLE
Dropbox upload error

### ISSUE THREAD

**Issue by Briochorama** [d0ugal/hassio-dropbox-upload#43]
Hi all,

I run HA on my raspberry pi, whithout duckdns or anything of the sort.
When I launch the addon, it seems to run fine until starting the snapshot upload to dropbox.

I have no idea how to fix this, and the following actions have been inneficient:
- Refresh app token.
- Change app type from _dropbox folder_ to _entire dropbox_.
- Restart HA, restart the addon, uninstall & reinstall the addon.

Following text is from the log:

> 2018-11-21 10:32:47,020 - INFO - Starting Snapshot backup
2018-11-21 10:32:47,145 - INFO - Found 2 snapshots
2018-11-21 10:32:47,147 - INFO - Backing up to Dropbox directory: /
2018-11-21 10:32:47,148 - INFO - Snapshot: (1/2)
2018-11-21 10:32:47,154 - WARNING - Snapshot ‘’ is not password protected. Always try to use passwords, particulary when uploading all your data to a snapshot to a third party.
2018-11-21 10:32:47,157 - INFO - Size: 910 KB
2018-11-21 10:32:47,158 - INFO - Created: 2018-11-19T18:24:06.500222+00:00
2018-11-21 10:32:47,483 - INFO - No existing snapshot in dropox with this name
Caught exception when calling dropbox_upload.dropbox.upload_file
Traceback (most recent call last):
File “/usr/lib/python3.6/site-packages/retrace.py”, line 289, in call
result = fn(*args, **kwargs)
File “/app/dropbox_upload/dropbox.py”, line 18, in upload_file
return dbx.files_upload(f, dest_path)
File “/usr/lib/python3.6/site-packages/dropbox/base.py”, line 2207, in files_upload
f,
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 274, in request
timeout=timeout)
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 365, in request_json_string_with_retry
timeout=timeout)
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 409, in request_json_string
type(request_binary))
TypeError: expected request_binary as binary type, got <class ‘_io.BufferedReader’>
Caught exception when calling dropbox_upload.dropbox.upload_file
Traceback (most recent call last):
File “/usr/lib/python3.6/site-packages/retrace.py”, line 289, in call
result = fn(*args, **kwargs)
File “/app/dropbox_upload/dropbox.py”, line 18, in upload_file
return dbx.files_upload(f, dest_path)
File “/usr/lib/python3.6/site-packages/dropbox/base.py”, line 2207, in files_upload
f,
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 274, in request
timeout=timeout)
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 365, in request_json_string_with_retry
timeout=timeout)
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 409, in request_json_string
type(request_binary))
TypeError: expected request_binary as binary type, got <class ‘_io.BufferedReader’>
2018-11-21 10:32:47,525 - ERROR - Unhandled error
Traceback (most recent call last):
File “/app/dropbox_upload/main.py”, line 35, in main
stats = backup.backup(dbx, cfg, snapshots)
File “/app/dropbox_upload/backup.py”, line 50, in backup
stats = process_snapshot(config, dbx, snapshot)
File “/app/dropbox_upload/backup.py”, line 86, in process_snapshot
dropbox.upload_file(dbx, path, target)
File “/usr/lib/python3.6/site-packages/retrace.py”, line 203, in wrapped_f
Caught exception when calling dropbox_upload.dropbox.upload_file
return Retry(*dargs, **dkwargs)(f, *args, **kw)
Traceback (most recent call last):
File “/usr/lib/python3.6/site-packages/retrace.py”, line 301, in call
self._limit.attempt(self.attempts)
File “/usr/lib/python3.6/site-packages/retrace.py”, line 289, in call
result = fn(*args, **kwargs)
File “/usr/lib/python3.6/site-packages/retrace.py”, line 142, in attempt
raise LimitReached()
File “/app/dropbox_upload/dropbox.py”, line 18, in upload_file
retrace.LimitReached
return dbx.files_upload(f, dest_path)
2018-11-21 10:32:47,531 - INFO - Sleeping for 60 minutes
File “/usr/lib/python3.6/site-packages/dropbox/base.py”, line 2207, in files_upload
f,
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 274, in request
timeout=timeout)
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 365, in request_json_string_with_retry
timeout=timeout)
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 409, in request_json_string
type(request_binary))
TypeError: expected request_binary as binary type, got <class ‘_io.BufferedReader’>
Caught exception when calling dropbox_upload.dropbox.upload_file
Traceback (most recent call last):
File “/usr/lib/python3.6/site-packages/retrace.py”, line 289, in call
result = fn(*args, **kwargs)
File “/app/dropbox_upload/dropbox.py”, line 18, in upload_file
return dbx.files_upload(f, dest_path)
File “/usr/lib/python3.6/site-packages/dropbox/base.py”, line 2207, in files_upload
f,
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 274, in request
timeout=timeout)
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 365, in request_json_string_with_retry
timeout=timeout)
File “/usr/lib/python3.6/site-packages/dropbox/dropbox.py”, line 409, in request_json_string
type(request_binary))
TypeError: expected request_binary as binary type, got <class ‘_io.BufferedReader’>

**Comment by ezar** [comment]
Same here!

**Comment by d0ugal** [comment]
I really don't know why this would be happening. Can you both describe your setups? What are you running HA and HASS.io on?

**Comment by albeseba86** [comment]
same here.
running Hass.io on raspberry pi. addons: duckdns, appdaemon, configurator, mariaDB, mosquitto, ssh and samba
My error:
`File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))
Caught exception when calling dropbox_upload.dropbox.upload_file
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/retrace.py", line 289, in __call__
2018-12-27 15:23:29,434 - ERROR - Unhandled error
Traceback (most recent call last):
    result = fn(*args, **kwargs)
  File "/app/dropbox_upload/__main__.py", line 35, in main
    stats = backup.backup(dbx, cfg, snapshots)
  File "/app/dropbox_upload/backup.py", line 50, in backup
  File "/app/dropbox_upload/dropbox.py", line 20, in upload_file
    stats = process_snapshot(config, dbx, snapshot)
  File "/app/dropbox_upload/backup.py", line 86, in process_snapshot
    upload_session_start_result = dbx.files_upload_session_start(f.read(CHUNK_SIZE))
    dropbox.upload_file(dbx, path, target)
  File "/usr/lib/python3.6/site-packages/retrace.py", line 203, in wrapped_f
  File "/usr/lib/python3.6/site-packages/dropbox/base.py", line 2395, in files_upload_session_start
    return Retry(*dargs, **dkwargs)(f, *args, **kw)
  File "/usr/lib/python3.6/site-packages/retrace.py", line 301, in __call__
    f,
    self._limit.attempt(self.attempts)
  File "/usr/lib/python3.6/site-packages/retrace.py", line 142, in attempt
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 274, in request
    raise LimitReached()
    timeout=timeout)
retrace.LimitReached
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 365, in request_json_string_with_retry`

**Comment by jabetcha** [comment]
This line is indicating a problem with the code at line 18 of dropbox.py

  File "/app/dropbox_upload/dropbox.py", line 18, in upload_file
    return dbx.files_upload(f, dest_path)

Error is this:

TypeError: expected request_binary as binary type, got <class '_io.BufferedReader'>

I saw some other articles indicating that code should be:
return dbx.files_upload(f.read(), dest_path)

I'd like to test this, but I'm having a difficult time finding the files on the system (new to HA)

**Comment by d0ugal** [comment]
Aha, that does seem like a logical fix. I’m currently away for the holidays but when I get back in a few days I can try it out.

Changing the code is a little tricky as it only exists in a container image. You can copy this full repo into your local addons and then change it there... check out the hass.io addon docs for steps.

Sorry for the brevity I’m on my phone.

**Comment by jabetcha** [comment]
I have tested my change on my hass.io install of HA and it is working now!

**Comment by d0ugal** [comment]
Super. Can you open a pull request?

**Comment by jabetcha** [comment]
I cannot get the file to push into the repo.

remote: Permission to d0ugal/hassio-dropbox-upload.git denied to jabetcha.
fatal: unable to access 'https://jabetcha@github.com/d0ugal/hassio-dropbox-upload.git/': The requested URL returned error: 403

**Comment by d0ugal** [comment]
Yeah, you need to fork the repo. Push to your fork and then open a pull request. Given it is a small change you can do this all via the GitHub website btw.

No worries if you don’t have time. I can do it over the next few days, just wanted you to have the credit!

**Comment by d0ugal** [comment]
I made a release yesterday with this fix. Seems to be working well with me. Please let me know if any of you hit this issue still.

**Comment by PrathikGopal** [comment]
Hey @d0ugal , im getting the errors, it never worked for me, I tried many things doesnt seem to move past. HA is on my raspberry pi, tried removing and readding addon, same errors.
```
2019-01-29 20:34:17,450 - INFO - Starting Snapshot backup
2019-01-29 20:34:17,458 - DEBUG - Auth headers: {'X-HASSIO-KEY': 'REDACTED'}
2019-01-29 20:34:17,494 - DEBUG - <Response [200]>
2019-01-29 20:34:17,496 - DEBUG - {'result': 'ok', 'data': {'snapshots': [{'slug': '0ce1fcea', 'name': 'Automated Backup 2019-01-28', 'date': '2019-01-28T17:37:08.585393+00:00', 'type': 'full', 'protected': True}]}}
2019-01-29 20:34:17,555 - INFO - Found 1 snapshots
2019-01-29 20:34:17,557 - INFO - Backing up to Dropbox directory: /
2019-01-29 20:34:17,557 - INFO - Snapshot: Automated Backup 2019-01-28 (1/1)
2019-01-29 20:34:17,561 - DEBUG - Slug: 0ce1fcea
2019-01-29 20:34:17,562 - INFO - Size: 389.87 MB
2019-01-29 20:34:17,563 - INFO - Created: 2019-01-28T17:37:08.585393+00:00
2019-01-29 20:34:17,564 - DEBUG - Uploading to: /0ce1fcea.tar
2019-01-29 20:34:18,056 - INFO - No existing snapshot in dropox with this name
Caught exception when calling dropbox_upload.dropbox.upload_file
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/retrace.py", line 289, in __call__
    result = fn(*args, **kwargs)
  File "/app/dropbox_upload/dropbox.py", line 20, in upload_file
    upload_session_start_result = dbx.files_upload_session_start(f.read(CHUNK_SIZE))
  File "/usr/lib/python3.6/site-packages/dropbox/base.py", line 2395, in files_upload_session_start
    f,
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 274, in request
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 365, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 449, in request_json_string
    timeout=timeout,
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))
Caught exception when calling dropbox_upload.dropbox.upload_file
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/retrace.py", line 289, in __call__
    result = fn(*args, **kwargs)
  File "/app/dropbox_upload/dropbox.py", line 20, in upload_file
    upload_session_start_result = dbx.files_upload_session_start(f.read(CHUNK_SIZE))
  File "/usr/lib/python3.6/site-packages/dropbox/base.py", line 2395, in files_upload_session_start
    f,
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 274, in request
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 365, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 449, in request_json_string
    timeout=timeout,
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))
2019-01-29 20:36:21,246 - ERROR - Unhandled error
Traceback (most recent call last):
  File "/app/dropbox_upload/__main__.py", line 35, in main
    stats = backup.backup(dbx, cfg, snapshots)
  File "/app/dropbox_upload/backup.py", line 50, in backup
    stats = process_snapshot(config, dbx, snapshot)
  File "/app/dropbox_upload/backup.py", line 86, in process_snapshot
    dropbox.upload_file(dbx, path, target)
  File "/usr/lib/python3.6/site-packages/retrace.py", line 203, in wrapped_f
    return Retry(*dargs, **dkwargs)(f, *args, **kw)
  File "/usr/lib/python3.6/site-packages/retrace.py", line 301, in __call__
    self._limit.attempt(self.attempts)
  File "/usr/lib/python3.6/site-packages/retrace.py", line 142, in attempt
    raise LimitReached()
retrace.LimitReached
2019-01-29 20:36:21,249 - INFO - Sleeping for 60 minutes

```
