### ISSUE TITLE
Exception when calling dropbox_upload.dropbox.upload_file

### ISSUE THREAD

**Issue by PrathikGopal** [d0ugal/hassio-dropbox-upload#48]
Im seeing the error upon addon startup, doesnt seem to move past this

```
2019-01-29 20:34:17,450 - INFO - Starting Snapshot backup
2019-01-29 20:34:17,458 - DEBUG - Auth headers: {'X-HASSIO-KEY': 'REDACTED'}
2019-01-29 20:34:17,494 - DEBUG - <Response [200]>
2019-01-29 20:34:17,496 - DEBUG - {'result': 'ok', 'data': {'snapshots': [{'slug': '0ce1fcea', 'name': 'Automated Backup 2019-01-28', 'date': '2019-01-28T17:37:08.585393+00:00', 'type': 'full', 'protected': True}]}}
2019-01-29 20:34:17,555 - INFO - Found 1 snapshots
2019-01-29 20:34:17,557 - INFO - Backing up to Dropbox directory: /
2019-01-29 20:34:17,557 - INFO - Snapshot: Automated Backup 2019-01-28 (1/1)
2019-01-29 20:34:17,561 - DEBUG - Slug: 0ce1fcea
2019-01-29 20:34:17,562 - INFO - Size: 389.87 MB
2019-01-29 20:34:17,563 - INFO - Created: 2019-01-28T17:37:08.585393+00:00
2019-01-29 20:34:17,564 - DEBUG - Uploading to: /0ce1fcea.tar
2019-01-29 20:34:18,056 - INFO - No existing snapshot in dropox with this name
Caught exception when calling dropbox_upload.dropbox.upload_file
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/retrace.py", line 289, in __call__
    result = fn(*args, **kwargs)
  File "/app/dropbox_upload/dropbox.py", line 20, in upload_file
    upload_session_start_result = dbx.files_upload_session_start(f.read(CHUNK_SIZE))
  File "/usr/lib/python3.6/site-packages/dropbox/base.py", line 2395, in files_upload_session_start
    f,
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 274, in request
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 365, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 449, in request_json_string
    timeout=timeout,
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))
Caught exception when calling dropbox_upload.dropbox.upload_file
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/retrace.py", line 289, in __call__
    result = fn(*args, **kwargs)
  File "/app/dropbox_upload/dropbox.py", line 20, in upload_file
    upload_session_start_result = dbx.files_upload_session_start(f.read(CHUNK_SIZE))
  File "/usr/lib/python3.6/site-packages/dropbox/base.py", line 2395, in files_upload_session_start
    f,
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 274, in request
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 365, in request_json_string_with_retry
    timeout=timeout)
  File "/usr/lib/python3.6/site-packages/dropbox/dropbox.py", line 449, in request_json_string
    timeout=timeout,
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out',))
2019-01-29 20:36:21,246 - ERROR - Unhandled error
Traceback (most recent call last):
  File "/app/dropbox_upload/__main__.py", line 35, in main
    stats = backup.backup(dbx, cfg, snapshots)
  File "/app/dropbox_upload/backup.py", line 50, in backup
    stats = process_snapshot(config, dbx, snapshot)
  File "/app/dropbox_upload/backup.py", line 86, in process_snapshot
    dropbox.upload_file(dbx, path, target)
  File "/usr/lib/python3.6/site-packages/retrace.py", line 203, in wrapped_f
    return Retry(*dargs, **dkwargs)(f, *args, **kw)
  File "/usr/lib/python3.6/site-packages/retrace.py", line 301, in __call__
    self._limit.attempt(self.attempts)
  File "/usr/lib/python3.6/site-packages/retrace.py", line 142, in attempt
    raise LimitReached()
retrace.LimitReached
2019-01-29 20:36:21,249 - INFO - Sleeping for 60 minutes

```

**Comment by d0ugal** [comment]
Looks like the upload keeps timing out, there are so many errors because it attempts to upload 5 times. I can't see an obvious issue here. How stable/fast is your internet upload?

**Comment by PrathikGopal** [comment]
I’ve got a good upload speed @ 10mbps. No network disconnects or any issues.

**Comment by PrathikGopal** [comment]
I’m not sure about this one , it’s started working by itself. I will test this further and report back.

**Comment by d0ugal** [comment]
Great, do let me know if the error returns.
