### ISSUE TITLE
DeleteError in logs

### ISSUE THREAD

**Issue by clarkd** [d0ugal/hassio-dropbox-upload#62]
Hi,

I regularly see the below error in my logs, and I'm not sure the addon is working as expected. It doesn't seem to clean up old backups from the local disk/dropbox.

```
2020-11-13 10:51:52,817 - INFO - Already found in Dropbox with the same hash
2020-11-13 10:51:52,817 - INFO - Uploads complete
2020-11-13 10:51:52,818 - INFO - Total size: 4.3 GB
2020-11-13 10:51:52,818 - INFO - Limiting snapshots to the 7 most recent
2020-11-13 10:51:52,836 - INFO - Deleting 22 snapshots
2020-11-13 10:51:52,836 - INFO - Deleting AutomatedBackup_2020-10-31 (slug: 887255d4
2020-11-13 10:51:54,309 - ERROR - Unhandled error
Traceback (most recent call last):
  File "/app/dropbox_upload/__main__.py", line 48, in main
    limit.limit_snapshots(dbx, cfg, snapshots)
  File "/app/dropbox_upload/limit.py", line 35, in limit_snapshots
    dbx.files_delete(path)
  File "/usr/lib/python3.8/site-packages/dropbox/base.py", line 1401, in files_delete
    r = self.request(
  File "/usr/lib/python3.8/site-packages/dropbox/dropbox.py", line 337, in request
    raise ApiError(res.request_id,
dropbox.exceptions.ApiError: ApiError('xxxx', DeleteError('path_lookup', LookupError('not_found', None)))
2020-11-13 10:51:54,311 - INFO - Sleeping for 60 minutes
```

Any thoughts?

**Comment by d0ugal** [comment]
Interesting. It looks like the backups are being created, but not cleaned up. I've not seen this error before and not really sure what it means. I'd guess you have 29 snapshots in dropbox? That must be taking quite a bit of space! :)

It is hard to know how to fix this as the error from dropbox doesn't give us much to go on.
