### ISSUE TITLE
dropbox full, keep uploading

### ISSUE THREAD

**Issue by astralrick** [d0ugal/hassio-dropbox-upload#63]
If your dropbox if full, home assistant will keep trying to upload your snapshots to dropbox but keep failing. Failed->try to upload->failed->try to upload (LOOP) end up using lots of your upload bandwidth without actually upload to dropbox

**Comment by d0ugal** [comment]
Good catch. Wonder how best to detect that

**Comment by astralrick** [comment]
I was scratching my head trying to find who ate up my bandwidth for uploading. Through enable/disable homeassistant add-ons. At last through my router saying "drop box".

**Comment by d0ugal** [comment]
Sorry about that! I have a unmetered connection, so wouldn’t have noticed

**Comment by astralrick** [comment]
No worries big thanks for the developing and sharing the add-ons. I do have unlimited connections but it keeps using my full upload bandwidth. Cheers

**Comment by d0ugal** [comment]
Is there a error in the logs you can share? I wonder if I can at least stop the retrying.

**Comment by astralrick** [comment]
for sure but I didn't look at the logs nor keeping it but i can make my dropbox full to find the error logs. Will do it tonight. Thanks

**Comment by astralrick** [comment]
2020-11-17 21:57:39,852 - INFO - Snapshot: Automated Backup 2020-11-07 (3/3)
2020-11-17 21:57:39,855 - INFO - Size: 96.16 MB
2020-11-17 21:57:39,856 - INFO - Created: 2020-11-07T09:00:00.046651+00:00
2020-11-17 21:57:40,096 - INFO - No existing snapshot in dropox with this name
2020-11-17 21:57:43,617 - INFO -   4 %
2020-11-17 21:57:50,098 - INFO -  12 %
2020-11-17 21:57:53,302 - INFO -  17 %
2020-11-17 21:58:00,006 - INFO -  25 %
2020-11-17 21:58:40,861 - INFO -  33 %
2020-11-17 21:58:47,571 - INFO -  42 %
2020-11-17 21:58:54,176 - INFO -  50 %
2020-11-17 21:59:00,675 - INFO -  58 %
2020-11-17 21:59:07,585 - INFO -  67 %
2020-11-17 21:59:14,121 - INFO -  75 %
2020-11-17 21:59:20,957 - INFO -  83 %
2020-11-17 22:00:17,261 - INFO -  92 %
2020-11-17 22:00:23,755 - INFO - 100 %
Caught exception when calling dropbox_upload.dropbox.upload_file
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/retrace.py", line 268, in __call__
    result = fn(*args, **kwargs)
  File "/app/dropbox_upload/dropbox.py", line 34, in upload_file
    dbx.files_upload_session_finish(f.read(CHUNK_SIZE), cursor, commit)
  File "/usr/lib/python3.8/site-packages/dropbox/base.py", line 3072, in files_upload_session_finish
    r = self.request(
  File "/usr/lib/python3.8/site-packages/dropbox/dropbox.py", line 337, in request
    raise ApiError(res.request_id,
dropbox.exceptions.ApiError: ApiError('fa540b6b06ca485dbc2e529825d1373c', UploadSessionFinishError('path', WriteError('insufficient_space', None)))
2020-11-17 22:00:28,110 - INFO -   4 %
repeat........

**Comment by astralrick** [comment]
1. dropbox full
2. snapshot name cannot be found in drop box-> need to backup to dropbox
3. upload but insufficient space
4. repeat uploading
